# ~/.config/starship.toml

add_newline = false
command_timeout = 1000
format = """$os$directory$git_branch$git_status$nodejs$kotlin$java$swift$rust$golang$aws$kubernetes
$character"""

[character]
success_symbol = '[❯](bold #7aa2f7)'
error_symbol = '[❯](bold #f7768e)'
vicmd_symbol = '[❮](bold #bb9af7)'

# ---

[os]
format = '[$symbol](bold #7aa2f7) '
disabled = false

[os.symbols]
Macos = '󰀵'
Arch = '󰣇'
Ubuntu = ''
Windows = ' '

# ---

[directory]
truncation_length = 3
truncation_symbol = '…/'
home_symbol = '󰋜 ~'
read_only_style = '#f7768e'
read_only = '  '
style = 'bold #7aa2f7'
format = 'at [$path]($style)[$read_only]($read_only_style) '

# ---

[git_branch]
symbol = ' '
format = 'on [$symbol$branch]($style)'
truncation_symbol = '…/'
style = 'bold #9ece6a'

[git_status]
format = '( [\($all_status$ahead_behind\)]($style))'
style = 'bold #9ece6a'
conflicted = '[ conflicted=${count}](#f7768e) '
up_to_date = '[󰘽 up-to-date](#9ece6a)'
untracked = '[󰋗 untracked=${count}](#f7768e) '
ahead = ' ahead=${count}'
diverged = ' ahead=${ahead_count}  behind=${behind_count}'
behind = ' behind=${count}'
stashed = '[ stashed=${count}](#7aa2f7) '
modified = '[󰛿 modified=${count}](#e0af68) '
staged = '[󰐗 staged=${count}](#9ece6a) '
renamed = '[󱍸 renamed=${count}](#e0af68) '
deleted = '[󰍶 deleted=${count}](#f7768e) '

# ---

[nodejs]
symbol = ' '
style = '#9ece6a'
format = '[$symbol$version]($style) '

[rust]
symbol = ' '
style = '#f7768e'
format = '[$symbol$version]($style) '

[golang]
symbol = ' '
style = '#7dcfff'
format = '[$symbol$version]($style) '

[kotlin]
symbol = ' '
style = '#bb9af7'
format = '[$symbol$version]($style) '
detect_files = ['build.gradle', 'build.gradle.kts', 'settings.gradle', 'settings.gradle.kts']
detect_folders = []
detect_extensions = []

[java]
symbol = ' '
style = '#f7768e'
format = '[$symbol$version]($style) '

[swift]
symbol = '󰛥 '
style = '#ff9e64'
format = '[$symbol$version]($style) '

[aws]
symbol = '󰸏 '
style = '#e0af68'
format = '[$symbol$profile]($style) '
disabled = false

[kubernetes]
format = 'via [󱃾 $context\($namespace\)](bold #bb9af7) '
disabled = false

[docker_context]
disabled = true

[vagrant]
disabled = true

[helm]
disabled = true

[terraform]
disabled = true
